# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: soleon.Percentage
PackageVersion: 2.1.8
InstallerType: portable
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/soleon/Percentage/releases/latest/download/Percentage.App.exe
  InstallerSha256: 10680443D734023641D4F9F28FA7D969DE68A5F375C3ABDCBDB2DBFB3807701C
ManifestType: installer
ManifestVersion: 1.9.0
